{{- if eq .chezmoi.os "linux" }}
[".config/nvim/"]
    type = "git-repo"
    url = "git@github.com:hojahoja/kickstart-modular.nvim.git"
    refreshPeriod = "168h"
{{- end }}
[".vim/pack/tpope/start/surround/plugin/surround.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/tpope/vim-surround/refs/heads/master/plugin/surround.vim"
    refreshPeriod = "672h"
[".vim/pack/tpope/start/commentary/plugin/commentary.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/tpope/vim-commentary/refs/heads/master/plugin/commentary.vim"
    refreshPeriod = "672h"
